# Generated by Django 6.0.3 on 2026-04-18 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0008_providerbranch_is_featured_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('health_talk', 'Health Talk'), ('medical_camp', 'Medical Camp'), ('webinar', 'Webinar'), ('screening', 'Health Screening'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('other', 'Other')], default='health_talk', max_length=50)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], default='onsite', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(default='Kenya', max_length=120)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('is_registration_required', models.BooleanField(default=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('is_paid', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='providers.provider')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
