# Generated by Django 6.0.3 on 2026-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
