# Generated by Django 6.0.3 on 2026-03-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userprofile_patientprofile_providerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
