# Generated by Django 6.0.3 on 2026-04-30 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0034_alter_professional_profile_photo_and_more'),
        ('providers', '0021_alter_providerservice_unique_together_and_more'),
        ('services', '0003_specialty_customservice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='providers.providerbranch')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='professionals.professional')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='services.service')),
                ('specialties', models.ManyToManyField(blank=True, to='services.specialty')),
            ],
            options={
                'unique_together': {('branch', 'service', 'professional')},
            },
        ),
    ]
