# Generated by Django 6.0.3 on 2026-05-01 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffering',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offerings', to='services.service'),
        ),
    ]
