# Generated by Django 6.0.3 on 2026-06-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0058_alter_professional_profile_photo'),
        ('services', '0005_alter_serviceoffering_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.professionaltype'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
