# Generated by Django 6.0.3 on 2026-06-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0059_alter_professional_profile_photo'),
        ('services', '0006_specialty_profession_alter_specialty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('name', 'profession'), name='unique_specialty_per_profession'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('slug', 'profession'), name='unique_specialty_slug_per_profession'),
        ),
    ]
