# Generated by Django 6.0.3 on 2026-06-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_specialty_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
