# Generated by Django 6.0.3 on 2026-06-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicecategory_icon_alter_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffering',
            name='specialties',
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='services.servicecategory'),
        ),
    ]
