# Generated by Django 6.0.3 on 2026-03-25 15:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_professional_title_alter_professional_user_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
