# Generated by Django 6.0.3 on 2026-03-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_alter_professional_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='consultancy_fee',
            new_name='consultation_fee',
        ),
    ]
