# Generated by Django 6.0.3 on 2026-03-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_rename_consultancy_fee_professional_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
