# Generated by Django 6.0.3 on 2026-03-26 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_alter_professional_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['professional_type__name', 'name']},
        ),
        migrations.AddField(
            model_name='professional',
            name='professional_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professionaltype'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='professional_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professionaltype'),
        ),
    ]
