# Generated by Django 6.0.3 on 2026-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_professionaltype_alter_specialty_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='icon',
        ),
        migrations.AddField(
            model_name='professionaltype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/'),
        ),
    ]
