# Generated by Django 6.0.3 on 2026-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_remove_specialty_icon_professionaltype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
