# Generated by Django 6.0.3 on 2026-04-17 11:55

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0011_professional_is_featured_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='offer_nhif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
