# Generated by Django 6.0.3 on 2026-04-17 11:57

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0012_professional_offer_nhif_alter_professional_banner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='offer_nhif',
            new_name='accepts_nhif',
        ),
        migrations.AlterField(
            model_name='professional',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
