# Generated by Django 6.0.3 on 2026-04-18 19:26

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0016_alter_professional_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
