# Generated by Django 6.0.3 on 2026-04-19 10:55

import apps.professionals.models.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0017_alter_professional_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_education', to='professionals.professional'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
