# Generated by Django 6.0.3 on 2026-04-20 11:05

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0018_alter_education_professional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='banner',
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
