# Generated by Django 6.0.3 on 2026-04-29 15:48

import apps.professionals.models.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0028_alter_professional_profile_photo_professionalservice'),
        ('services', '0003_specialty_customservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalbranch',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.specialty'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialties',
            field=models.ManyToManyField(to='services.specialty'),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
