# Generated by Django 6.0.3 on 2026-04-30 05:20

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0030_alter_professional_profile_photo'),
        ('services', '0003_specialty_customservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, to='services.specialty'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
