# Generated by Django 6.0.3 on 2026-04-30 16:45

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0033_alter_professional_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
        migrations.DeleteModel(
            name='ProfessionalService',
        ),
    ]
