# Generated by Django 6.0.3 on 2026-05-04 05:35

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0039_alter_professional_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='title',
            field=models.CharField(choices=[('dr', 'Doctor'), ('prof', 'Professor'), ('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss')], default='dr', max_length=10),
        ),
    ]
