# Generated by Django 6.0.3 on 2026-05-04 11:43

import apps.professionals.models.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0040_alter_professional_profile_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
