# Generated by Django 6.0.3 on 2026-05-22 09:14

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0045_alter_professional_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
