# Generated by Django 6.0.3 on 2026-05-25 05:04

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0046_alter_operatinghours_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
