# Generated by Django 6.0.3 on 2026-05-30 09:46

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0048_alter_professional_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='consultation_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professional',
            name='introduction_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
