# Generated by Django 6.0.3 on 2026-06-02 09:09

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0049_professional_consultation_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to='professionals/profile/'),
        ),
    ]
