# Generated by Django 6.0.3 on 2026-06-07 08:09

import apps.professionals.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0055_alter_professional_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profile_photo',
            field=models.ImageField(upload_to="professionals/profile/"),
        ),
    ]
