# Generated by Django 6.0.3 on 2026-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_for',
            field=models.CharField(choices=[('provider', 'Provider'), ('professional', 'Professional'), ('all', 'All')], max_length=30, null=True),
        ),
    ]
