# Generated by Django 6.0.3 on 2026-04-09 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_providerbranch_is_featured_manual'),
        ('subscriptions', '0002_alter_plan_plan_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeaturedSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_subscriptions', to='providers.providerbranch')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_subscriptions', to='subscriptions.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'is_active'], name='subscriptio_branch__8c84e5_idx'), models.Index(fields=['start_date', 'end_date'], name='subscriptio_start_d_879b73_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('branch',), name='unique_active_subscription_per_branch')],
            },
        ),
    ]
