# Generated by Django 6.0.3 on 2026-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_priority_featuredsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
