# Generated by Django 6.0.3 on 2026-05-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0023_alter_clinicsession_end_time_and_more'),
        ('subscriptions', '0004_plan_is_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='provider',
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='providers.providerbranch'),
        ),
    ]
