# Generated by Django 6.0.3 on 2026-03-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='providerbranch',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='providers.provider'),
        ),
    ]
