# Generated by Django 6.0.3 on 2026-03-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_provider_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerbranch',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
