# Generated by Django 6.0.3 on 2026-03-25 15:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_providerbranch_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchservice',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
