# Generated by Django 6.0.3 on 2026-04-08 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_branchservice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='providers.providerbranch'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
