# Generated by Django 6.0.3 on 2026-04-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_operatinghours_branch_alter_provider_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
