# Generated by Django 6.0.3 on 2026-04-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_alter_provider_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='branch',
            field=models.OneToOneField(limit_choices_to={'provider_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='providers.providerbranch'),
        ),
        migrations.AlterField(
            model_name='hospitalward',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_wards', to='providers.providerbranch'),
        ),
    ]
