# Generated by Django 6.0.3 on 2026-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_hospitalprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerbranch',
            name='is_featured_manual',
            field=models.BooleanField(default=False),
        ),
    ]
