# Generated by Django 6.0.3 on 2026-04-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_providerbranch_is_featured_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchservice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='providers.providerbranch'),
        ),
        migrations.AlterField(
            model_name='branchservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='providers.service'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.providerbranch'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.service'),
        ),
    ]
