# Generated by Django 6.0.3 on 2026-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_alter_branchservice_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='accepts_nhif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
