# Generated by Django 6.0.3 on 2026-04-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_hospitalprofile_accepts_nhif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='branch',
            field=models.OneToOneField(limit_choices_to={'provider__provider_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='providers.providerbranch'),
        ),
    ]
