# Generated by Django 6.0.3 on 2026-04-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_alter_hospitalprofile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalward',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_type', to='providers.wardtype'),
        ),
    ]
