# Generated by Django 6.0.3 on 2026-04-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_alter_hospitalward_ward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalward',
            name='ward_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards_type', to='providers.wardtype'),
        ),
    ]
