# Generated by Django 6.0.3 on 2026-04-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_alter_hospitalward_ward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalward',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_wards', to='providers.providerbranch'),
        ),
    ]
