# Generated by Django 6.0.3 on 2026-04-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_alter_hospitalward_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='has_pharmacy',
            field=models.BooleanField(default=False),
        ),
    ]
