# Generated by Django 6.0.3 on 2026-04-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_hospitalprofile_has_pharmacy'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='services.service'),
        ),
        migrations.AlterField(
            model_name='branchservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='services.service'),
        ),
        migrations.AddField(
            model_name='branchservice',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='branchservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='branchservice',
            unique_together={('branch', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='providerservice',
            unique_together={('provider', 'service')},
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
