# Generated by Django 6.0.3 on 2026-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_branchservice_specialties'),
        ('services', '0003_specialty_customservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, to='services.specialty'),
        ),
    ]
