# Generated by Django 6.0.3 on 2026-04-30 11:53

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0032_alter_professional_profile_photo'),
        ('providers', '0018_providerservice_specialties'),
        ('services', '0003_specialty_customservice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to='')),
                ('bio', tinymce.models.HTMLField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.providerbranch')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professionaltype')),
                ('specialties', models.ManyToManyField(to='services.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_week', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.providerbranch')),
                ('specialists', models.ManyToManyField(blank=True, to='providers.specialist')),
            ],
        ),
    ]
