# Generated by Django 6.0.3 on 2026-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0019_specialist_clinicsession'),
        ('services', '0003_specialty_customservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchservice',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='services.specialty'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='services.specialty'),
        ),
    ]
