# Generated by Django 6.0.3 on 2026-04-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0020_alter_branchservice_specialties_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='providerservice',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providerservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='providerservice',
            name='specialties',
        ),
        migrations.DeleteModel(
            name='BranchService',
        ),
        migrations.DeleteModel(
            name='ProviderService',
        ),
    ]
