# Generated by Django 6.0.3 on 2026-05-01 19:11

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0021_alter_providerservice_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicsession',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='clinicsession',
            name='day_week',
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='max_patients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='slot_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicsession',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicsession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_sessions', to='providers.providerbranch'),
        ),
    ]
