# Generated by Django 6.0.3 on 2026-05-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0022_rename_name_clinicsession_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
