# Generated by Django 6.0.3 on 2026-05-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0023_alter_clinicsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
