# Generated by Django 6.0.3 on 2026-06-02 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0024_alter_operatinghours_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='trust_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
