# Generated by Django 6.0.3 on 2026-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0025_hospitalprofile_trust_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4'), ('level_5', 'Level 5'), ('level_6', 'Level 6')], max_length=10),
        ),
    ]
