# Generated by Django 6.0.3 on 2026-06-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0026_alter_hospitalprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='providers.providerbranch'),
        ),
    ]
