# Generated by Django 6.0.3 on 2026-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0027_alter_hospitalprofile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerbranch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='providerbranch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
