# Generated by Django 6.0.3 on 2026-07-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0028_alter_providerbranch_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='tiktok',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='twitter_x',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='providerbranch',
            name='bookings_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='providerbranch',
            name='building_floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
