# Generated by Django 6.0.3 on 2026-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0029_hospitalprofile_facebook_hospitalprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('mission', 'Mission/Faith-based'), ('ngo', 'NGO')], max_length=20),
        ),
    ]
