# Generated by Django 6.0.3 on 2026-05-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_email_booking_name_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
