# Generated by Django 6.0.3 on 2026-05-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_phone'),
        ('services', '0005_alter_serviceoffering_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.serviceoffering'),
        ),
    ]
