# Generated by Django 6.0.3 on 2026-05-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_service'),
        ('professionals', '0042_alter_professional_profile_photo'),
        ('providers', '0023_alter_clinicsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_bookings', to='providers.providerbranch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_bookings', to='professionals.professional'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to='providers.provider'),
        ),
    ]
