# Generated by Django 6.0.3 on 2026-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
